apiVersion: apps/v1
kind: Deployment
metadata:
  name: cctv-service
  labels:
    app: cctv-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cctv-service
  template:
    metadata:
      labels:
        app: cctv-service
    spec:
      containers:
        - name: cctv-service
          image: "monat96/alp-ca-cctv-service:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5