version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  cctv-service:
    build: ./backend/cctv-service
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cctv:5432/cctvdb
      # SPRING_DATASOURCE_USERNAME: user
      # SPRING_DATASOURCE_PASSWORD: pass
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  health-check-service:
    build: ./backend/health-check-service
    ports:
      - "8083:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-health:5432/healthdb
      # SPRING_DATASOURCE_USERNAME: user
      # SPRING_DATASOURCE_PASSWORD: pass
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  notification-service:
    build: ./backend/notification-service
    ports:
      - "8085:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notification:5432/notificationdb
      # SPRING_DATASOURCE_USERNAME: user
      # SPRING_DATASOURCE_PASSWORD: pass
      # SPRING_MAIL_HOST: smtp.example.com
      # SPRING_MAIL_PORT: 587
      # SPRING_MAIL_USERNAME: your-email@example.com
      # SPRING_MAIL_PASSWORD: your-email-password
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  issue-service:
    build: ./backend/issue-service
    ports:
      - "8084:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-issue:5432/issuedb
      # SPRING_DATASOURCE_USERNAME: user
      # SPRING_DATASOURCE_PASSWORD: pass
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

