server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

  cloud:
    function:
      definition: issueEvent
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        issue-event-in:
          destination: issue-event-in
          contentType: application/json
          group: issue-service
        issue-event-out:
          destination: notificationEvent-in-0
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug