apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  labels:
    app: health-check-service
spec:
  selector:
    app: health-check-service
  ports:
    - port: 8080
      targetPort: 8080