spring:
  cloud:
    gateway:
      routes:
        - id: cctv-service
          uri: http://localhost:8081
          predicates:
            - Path=/cctvs/**
        - id: health-check-service
          uri: http://localhost:8083
          predicates:
            - Path=/health-checks/**
        - id: issue-service
          uri: http://localhost:8084
          predicates:
            - Path=/issues/**
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**
      globalcors:
        cors-configurations:
            '[/**]':
                allowed-origin-patterns:
                  -  "*"
                allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                allowedHeaders:
                    - "*"
                allowCredentials: false
                maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

