server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: cctv-service
          uri: http://cctv-service:8080
          predicates:
            - Path=/cctvs/**
        - id: health-check-service
          uri: http://health-check-service:8080
          predicates:
            - Path=/health-checks/**
        - id: issue-service
          uri: http://issue-service:8080
          predicates:
            - Path=/issues/**
        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/notifications/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
