server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

  cloud:
    stream:
      kafka:
        binder:
          brokers: http://my-kafka:9092
      bindings:
        cctvCreated:
          destination: cctv-created-topic
          contentType: application/json