server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        cctv-event-in:
          destination: cctv-event
          contentType: application/json
          group: cctv-service
        cctv-event-out:
            destination: health-check-event
            contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug